### ISSUE TITLE
Tables fix

### ISSUE THREAD

**Issue by planecobra** [RealLubY/Azoth#4]
I know how to edit tables but how would i change the time in between bullets because the ak fires the 1st bullet on click 2nd 121.96149709966872 ms and 3rd 92.6333814724611 ms and so on how would i set it to ajust for those changes?

**Comment by Xoom7573** [comment]
idk But would make the ak way more accurate! if u find a solution let me know ill be looking into it aswell!

**Comment by planecobra** [comment]
Yes I have implemented a way where it basically gets the values from the actual game and then converted to pixels so it’s pretty much perfect but I’m still working on the control tires which is a little tricky

**Comment by mdotrush** [comment]
how do u open the menu i dont understand
